authorName: default
experimentName: bert_adl
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 36
nniManagerIp: 10.20.41.120
trainingServicePlatform: adl
# specify your search space file
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  builtinTunerName: TPE
  classArgs:
   optimize_mode: minimize
trial:
  # file position in your docker container
  command: python3 /workspace/texar-pytorch/examples/bert/bert_classifier_adaptive_nni.py
  codeDir: .
  gpuNum: 1
  image: registry.petuum.com/dev/nni:texar-bert-classifier
  imagePullSecrets:
    - name: stagingsecret